# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d703b8a1a0df81ec4cf00651964258e63d6207c7e1ade654dee04707fd5965783984de58b644efd589f0ea9169e2070756d6acf330d7630f8d5c991a0bf07c

test:
  secret_key_base: e5400bace51cfabd40d8be6812202137565a9e6657fb10aea6a73315b54d3ef5dea11dfb44de0a3ba9bc84ee0d675ca964bd99366ee04542a5abde523ddd78d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
